# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-28 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='info',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='type',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
